[package]
name = "rust-chibi-jwt"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
hmac = "0.12.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
sha2 = "0.10.8"
thiserror = "1.0.63"
